<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="cable_robot_platform">

    <!-- Parameters -->
    <xacro:arg name="platform_length" default="0.5"/>  <!-- Length of the platform (x-axis) -->
    <xacro:arg name="platform_width" default="0.5"/>   <!-- Width of the platform (y-axis) -->
    <xacro:arg name="platform_height" default="0.1"/>  <!-- Height of the platform (z-axis) -->
    <xacro:arg name="attachment_radius" default="0.02"/> <!-- Radius of attachment points -->
    <xacro:arg name="attachment_height" default="0.05"/> <!-- Height of attachment points above platform -->

    <!-- Platform Link -->
    <link name="platform">
        <!-- Visual Properties -->
        <visual>
            <geometry>
                <box size="$(arg platform_length) $(arg platform_width) $(arg platform_height)"/>
            </geometry>
            <material name="blue">
                <color rgba="0 0 1 1"/>
            </material>
        </visual>
        <!-- Collision Properties -->
        <collision>
            <geometry>
                <box size="$(arg platform_length) $(arg platform_width) $(arg platform_height)"/>
            </geometry>
        </collision>
        <!-- Inertial Properties -->
        <inertial>
            <mass value="1.0"/>
            <inertia 
                ixx="0.021666666666666667" ixy="0.0" ixz="0.0" 
                iyy="0.021666666666666667" iyz="0.0" 
                izz="0.041666666666666664"/>
        </inertial>
    </link>

    <!-- Floating Joint to Spawn in Gazebo -->
    <joint name="floating_joint" type="floating">
        <parent link="world"/>
        <child link="platform"/>
    </joint>

    <!-- Attachment Points -->
    <!-- Attachment Point 1 -->
    <link name="attachment_point_1">
        <visual>
            <geometry>
                <sphere radius="$(arg attachment_radius)"/>
            </geometry>
            <material name="red">
                <color rgba="1 0 0 1"/>
            </material>
        </visual>
        <inertial>
            <mass value="0.01"/>
            <inertia 
                ixx="0.0001" ixy="0.0" ixz="0.0" 
                iyy="0.0001" iyz="0.0" 
                izz="0.0001"/>
        </inertial>
    </link>
    <joint name="attachment_joint_1" type="fixed">
        <parent link="platform"/>
        <child link="attachment_point_1"/>
        <origin xyz="${arg.platform_length / 2} ${arg.platform_width / 2} ${arg.attachment_height}" rpy="0 0 0"/>
    </joint>

    <!-- Attachment Point 2 -->
    <link name="attachment_point_2">
        <visual>
            <geometry>
                <sphere radius="$(arg attachment_radius)"/>
            </geometry>
            <material name="red">
                <color rgba="1 0 0 1"/>
            </material>
        </visual>
        <inertial>
            <mass value="0.01"/>
            <inertia 
                ixx="0.0001" ixy="0.0" ixz="0.0" 
                iyy="0.0001" iyz="0.0" 
                izz="0.0001"/>
        </inertial>
    </link>
    <joint name="attachment_joint_2" type="fixed">
        <parent link="platform"/>
        <child link="attachment_point_2"/>
        <origin xyz="${-arg.platform_length / 2} ${arg.platform_width / 2} ${arg.attachment_height}" rpy="0 0 0"/>
    </joint>

    <!-- Attachment Point 3 -->
    <link name="attachment_point_3">
        <visual>
            <geometry>
                <sphere radius="$(arg attachment_radius)"/>
            </geometry>
            <material name="red">
                <color rgba="1 0 0 1"/>
            </material>
        </visual>
        <inertial>
            <mass value="0.01"/>
            <inertia 
                ixx="0.0001" ixy="0.0" ixz="0.0" 
                iyy="0.0001" iyz="0.0" 
                izz="0.0001"/>
        </inertial>
    </link>
    <joint name="attachment_joint_3" type="fixed">
        <parent link="platform"/>
        <child link="attachment_point_3"/>
        <origin xyz="${arg.platform_length / 2} ${-arg.platform_width / 2} ${arg.attachment_height}" rpy="0 0 0"/>
    </joint>

    <!-- Attachment Point 4 -->
    <link name="attachment_point_4">
        <visual>
            <geometry>
                <sphere radius="$(arg attachment_radius)"/>
            </geometry>
            <material name="red">
                <color rgba="1 0 0 1"/>
            </material>
        </visual>
        <inertial>
            <mass value="0.01"/>
            <inertia 
                ixx="0.0001" ixy="0.0" ixz="0.0" 
                iyy="0.0001" iyz="0.0" 
                izz="0.0001"/>
        </inertial>
    </link>
    <joint name="attachment_joint_4" type="fixed">
        <parent link="platform"/>
        <child link="attachment_point_4"/>
        <origin xyz="${-arg.platform_length / 2} ${-arg.platform_width / 2} ${arg.attachment_height}" rpy="0 0 0"/>
    </joint>

</robot>