<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- Include pillar properties -->
    <xacro:include filename="$(find CDPRX)/urdf/properties/pillar_properties.xacro"/>
    
    <!-- Single pillar macro -->
    <xacro:macro name="frame_pillar" params="prefix parent position_x position_y height *origin outlet_heights:=^">
        <!-- Base plate -->
        <link name="${prefix}_base">
            <visual>
                <geometry>
                    <box size="${pillar_base_length} ${pillar_base_width} ${pillar_base_height}"/>
                </geometry>
                <material name="base_material">
                    <color rgba="0.3 0.3 0.3 1"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <box size="${pillar_base_length} ${pillar_base_width} ${pillar_base_height}"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="${base_mass}"/>
                <inertia 
                    ixx="${base_ixx}" ixy="0" ixz="0" 
                    iyy="${base_iyy}" iyz="0" 
                    izz="${base_ixx}"/>
            </inertial>
        </link>

        <!-- Joint to parent -->
        <joint name="${prefix}_base_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="${prefix}_base"/>
            <origin xyz="${position_x} ${position_y} 0" rpy="0 0 0"/>
        </joint>

        <!-- Vertical pillar -->
        <link name="${prefix}_pillar">
            <visual>
                <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${pillar_width} ${pillar_length} ${height}"/>
                </geometry>
                <material name="pillar_material">
                    <color rgba="0.7 0.7 0.7 1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${pillar_width} ${pillar_length} ${height}"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
                <mass value="${pillar_mass}"/>
                <inertia 
                    ixx="${pillar_ixx}" ixy="0" ixz="0" 
                    iyy="${pillar_iyy}" iyz="0" 
                    izz="${(pillar_mass/12.0) * (pillar_width*pillar_width + pillar_length*pillar_length)}"/>
            </inertial>
        </link>

        <!-- Connect pillar to base -->
        <joint name="${prefix}_pillar_joint" type="fixed">
            <parent link="${prefix}_base"/>
            <child link="${prefix}_pillar"/>
            <origin xyz="0 0 ${pillar_base_height}" rpy="0 0 0"/>
        </joint>

        <!-- Generate cable outlets -->
        <xacro:macro name="generate_outlets" params="n">
            <xacro:if value="${n > 0}">
                <!-- Calculate outlet position to face frame center -->
                <xacro:property name="angle" value="${atan2(position_y, position_x)}"/>
                
                <!-- Create outlet -->
                <link name="${prefix}_outlet_${n}">
                    <visual>
                        <geometry>
                            <sphere radius="${outlet_radius}"/>
                        </geometry>
                        <material name="outlet_point">
                            <color rgba="1 0 0 1"/>
                        </material>
                    </visual>
                    <collision>
                        <geometry>
                            <sphere radius="${outlet_radius}"/>
                        </geometry>
                    </collision>
                </link>

                <!-- Position outlet on inner corner facing frame center -->
                <joint name="${prefix}_outlet_${n}_joint" type="fixed">
                    <parent link="${prefix}_pillar"/>
                    <child link="${prefix}_outlet_${n}"/>
                    <origin 
                        xyz="${-(pillar_width/2 - outlet_offset) * cos(angle)} 
                             ${-(pillar_length/2 - outlet_offset) * sin(angle)} 
                             ${outlet_heights[n-1]}" 
                        rpy="0 0 0"/>
                </joint>

                <!-- Recursive call for next outlet -->
                <xacro:generate_outlets n="${n-1}"/>
            </xacro:if>
        </xacro:macro>

        <!-- Generate outlets for this pillar -->
        <xacro:generate_outlets n="${len(outlet_heights)}"/>
    </xacro:macro>
</robot>