<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- Modular winch system macro -->
    <xacro:macro name="modular_winch" params="name parent drum_radius drum_length gear_ratio *origin">
        <!-- Motor housing -->
        <link name="${name}_housing">
            <visual>
                <geometry>
                    <box size="0.2 0.2 0.2"/>
                </geometry>
                <material name="motor_housing">
                    <color rgba="0.2 0.2 0.2 1"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <box size="0.2 0.2 0.2"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="2.0"/>
                <inertia ixx="0.1" ixy="0" ixz="0" 
                         iyy="0.1" iyz="0" izz="0.1"/>
            </inertial>
        </link>

        <!-- Mount motor to parent -->
        <joint name="${name}_mount" type="fixed">
            <parent link="${parent}"/>
            <child link="${name}_housing"/>
            <xacro:insert_block name="origin"/>
        </joint>

        <!-- Drum link -->
        <link name="${name}_drum">
            <visual>
                <geometry>
                    <cylinder radius="${drum_radius}" length="${drum_length}"/>
                </geometry>
                <material name="drum_material">
                    <color rgba="0.8 0.8 0.8 1"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${drum_radius}" length="${drum_length}"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="1.0"/>
                <inertia 
                    ixx="${(1.0/12) * (3*drum_radius*drum_radius + drum_length*drum_length)}"
                    iyy="${(1.0/12) * (3*drum_radius*drum_radius + drum_length*drum_length)}"
                    izz="${0.5 * drum_radius*drum_radius}"
                    ixy="0" ixz="0" iyz="0"/>
            </inertial>
        </link>

        <!-- Drum rotation joint -->
        <joint name="${name}_spin" type="continuous">
            <parent link="${name}_housing"/>
            <child link="${name}_drum"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <axis xyz="0 0 1"/>
            <dynamics damping="0.1" friction="0.1"/>
        </joint>

        <!-- Cable output mount point -->
        <xacro:cable_mount name="${name}_output" parent="${name}_drum">
            <origin xyz="0 0 ${drum_length/2}" rpy="0 0 0"/>
        </xacro:cable_mount>

        <!-- Add transmission for motor control -->
        <transmission name="${name}_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${name}_spin">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="${name}_motor">
                <mechanicalReduction>${gear_ratio}</mechanicalReduction>
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </actuator>
        </transmission>

        <!-- Gazebo-specific properties -->
        <gazebo reference="${name}_housing">
            <material>Gazebo/DarkGrey</material>
        </gazebo>

        <gazebo reference="${name}_drum">
            <material>Gazebo/Grey</material>
            <mu1>0.2</mu1>
            <mu2>0.2</mu2>
        </gazebo>
    </xacro:macro>
</robot>