<?xml version="1.0"?>
<!-- Save as ~/git/CDPRX/cdprx/urdf/test_robot.urdf.xacro -->
<robot name="cdpr_test" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- Include properties -->
    <xacro:property name="frame_height" value="2.0"/>
    <xacro:property name="frame_width" value="2.0"/>
    <xacro:property name="frame_length" value="2.0"/>
    
    <!-- World link -->
    <link name="world">
        <visual>
            <geometry>
                <sphere radius="0.02"/>
            </geometry>
            <material name="red">
                <color rgba="1 0 0 1"/>
            </material>
        </visual>
    </link>

    <!-- Simple test frame -->
    <link name="test_frame">
        <visual>
            <geometry>
                <box size="${frame_length} ${frame_width} ${frame_height}"/>
            </geometry>
            <material name="blue">
                <color rgba="0 0 1 0.5"/>
            </material>
        </visual>
    </link>

    <joint name="world_to_frame" type="fixed">
        <parent link="world"/>
        <child link="test_frame"/>
        <origin xyz="0 0 ${frame_height/2}" rpy="0 0 0"/>
    </joint>
</robot>